config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'questions#index'

  concern :votable do
    patch :vote_up, on: :member
    patch :vote_down, on: :member
    patch :cancel_vote, on: :member
  end

  resources :questions do
    concerns :votable
    resources :answers, shallow: true do
      patch :best, on: :member
      concerns :votable
    end
  end

  resources :attachments, only: [:destroy]

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true

  scope :ordered, -> { order(best: :desc) }

  include Attachable
  include Votable

  def best!
    prev_best = question.answers.where(best: true).first
    transaction do
      prev_best&.update!(best: false)
      update!(best: true)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true, optional: true

  mount_uploader :file, FileUploader
end

app/models/concerns/attachable.rb
module Attachable
  extend ActiveSupport::Concern

  included do
    has_many :attachments, as: :attachable
    accepts_nested_attributes_for :attachments, reject_if: :all_blank
  end
end

app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :votable
  end

  def vote(user, value)
    return if voted?(user)

    transaction do
      votes.create!(user: user, value: value)
      if value == 1
        self.class.increment_counter(:rating, self)
      else
        self.class.decrement_counter(:rating, self)
      end
      reload
    end

  end

  def cancel_vote(user)
    return unless voted?(user)

    transaction do
      if vote_by(user).value == 1
        self.class.decrement_counter(:rating, self)
      else
        self.class.increment_counter(:rating, self)
      end
      vote_by(user).destroy
      reload
    end
  end

  def vote_by(user)
    votes.find_by(user: user)
  end

  private

  def voted?(user)
    user.votes.exists?(votable: self)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, :body, presence: true

  include Attachable
  include Votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
  has_many :votes

  def author_of?(resource)
    resource.user_id == id
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true, optional: true
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :set_answer, only: [:destroy, :update, :best]
  after_action :publish_answer, only: [:create]

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    if current_user.author_of?(@answer)
      @question = @answer.question
      @answer.update(answer_params)
    end
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy
    else
      flash[:notice] = 'You can not delete this answer'
    end
  end

  def best
    if current_user.author_of?(@answer.question)
      @answer.best!
    else
      flash[:notice] = 'You can not set best answer'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    data = {
        question: @question,
        answer: @answer,
        attachments: @answer.attachments,
        author: @answer.user
    }
    ActionCable.server.broadcast("question_#{@question.id}_answers", data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]

  def destroy
    @attachment = Attachment.find(params[:id])
    if current_user.author_of?(@attachment.attachable)
      @attachment.destroy
      flash[:notice] = 'Attachment successfully deleted'
    else
      flash[:notice] = 'You can not to delete this attachment'
    end
  end
end

app/controllers/concerns/voted.rb
module Voted
  extend ActiveSupport::Concern

  included do
    before_action :set_votable, only: [:vote_up, :vote_down, :cancel_vote]
  end

  def vote_up
    vote +1
  end

  def vote_down
    vote -1
  end

  def cancel_vote
    @votable.cancel_vote(current_user)
    success_respond
  end

  private

  def model_klass
    controller_name.classify.constantize
  end

  def set_votable
    @votable = model_klass.find(params[:id])
  end

  def vote(value)
    if @votable.vote(current_user, value)
      success_respond
    else
      error_respond('Something went wrong')
    end
  end

  def success_respond
    json_respond(@votable.rating)
  end

  def json_respond(content, status = 200)
    render json: { id: @votable.id, content: content, votable_type: @votable.class.name.downcase }, status: status
  end

  def error_respond(message)
    json_respond(message, 403)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_question, only: [:show, :destroy, :update]

  after_action :publish_question, only: [:create]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    @answer.attachments.build
    gon.current_user = current_user if current_user
  end

  def new
    @question = Question.new
    @question.attachments.build
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def update
    @question.update(question_params) if current_user.author_of?(@question)
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
    end
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
        'questions',
        ApplicationController.render(
          partial: 'questions/question_title',
          locals: { question: @question }
        )
    )
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div id="answer-#{answer.id}"
    - if answer.best?
      .best-label
        p = 'Best answer'
    p = answer.body
    = render 'common/attachments', resource: answer

    div class='vote' id="answer-rating-#{answer.id}"
      | rating: #{answer.rating}
    = render 'common/vote', resource: answer
    - if current_user&.author_of?(answer.question)
      = link_to 'Mark as best ', best_answer_path(answer), remote: true, method: :patch, class: 'best-answer-link', data: {answer_id: answer.id}
    - if current_user&.author_of?(answer)
      = link_to 'Delete answer ', answer, remote: true, method: :delete, class: 'delete-answer-link', data: { answer_id: answer.id }
      = link_to 'Edit ', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      p = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          = f.label :body, 'Answer'
          = f.text_area :body
          = f.submit 'Save'

app/views/answers/best.js.erb
$('.best-label').remove();
$('#answer-<%= @answer.id %>').prependTo('.answers');
$('#answer-<%= @answer.id %>').prepend('<p class="best-label"> Best answer: </p>');

app/views/answers/create.js.erb
$('#error').remove();
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answers').append('<div id="error"><%= j message %></div>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.notice').remove();
$('#answer-<%= @answer.id %>').remove();

app/views/answers/update.js.erb
$('#error').remove();
$('.notice').remove();
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
  $('.answers').append('<div id="error"><%= j message %></div>');
<% end %>
<% else %>
  $('#answer-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>

app/views/attachments/destroy.js.erb
$('#attachment-<%= @attachment.id %>').remove();

app/views/common/_attachment_fields.html.slim
.nested-fields
  = f.label :file
  = f.file_field :file

app/views/common/_attachments.html.slim
p Attachments:
ul
  - resource.attachments.each do |a|
    li id = "attachment-#{a.id}"
      = link_to a.file.identifier, a.file.url
      - if current_user&.author_of?(resource)
        = link_to ' Delete file', a, remote: true, method: :delete

app/views/common/_errors.html.slim
- if resource.errors.any?
  #error_explanation
    ul
      - resource.errors.full_messages.each do |message|
        li = message

app/views/common/_vote.html.slim
- if current_user && !current_user.author_of?(resource)
  = link_to 'Vote up ', polymorphic_url(resource, action: :vote_up), method: :patch, remote: true, class: 'vote-link'
  = link_to 'Vote down ', polymorphic_url(resource, action: :vote_down), method: :patch, remote: true, class: 'vote-link'
  = link_to 'Cancel vote ', polymorphic_url(resource, action: :cancel_vote), method: :patch, remote: true, class: 'vote-link'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Qna"
    = Gon::Base.render_data
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = action_cable_meta_tag
    = javascript_include_tag "application"
      /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#"Qna
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            - if user_signed_in?
              li = link_to 'Sign out', destroy_user_session_path(@user), method: :delete
            - else
              li = link_to 'Sign in', new_user_session_path
              li = link_to 'Sign up', new_user_registration_path
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      footer
        p &copy; Company 2017

app/views/questions/_question.html.slim
h1 = question.title
p = question.body
= render 'common/attachments', resource: question

div class='question-rating' id="question-rating-#{question.id}"
  = question.rating
= render 'common/vote', resource: question

- if current_user&.author_of?(question)
  = link_to 'Delete question ', question_path, method: :delete
  = link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: question.id }
  = form_for question, remote: true, html: { id: "edit-question-#{question.id}" } do |f|
    = f.label :title, 'Title'
    = f.text_area :title
    = f.label :body, 'Body'
    = f.text_area :body
    = f.submit 'Save'

app/views/questions/_question_title.html.slim
li  = link_to question.title, question_path(question)

app/views/questions/index.html.slim
h1 Questions
ul class='questions-list'
  - @questions.each do |question|
    = render 'question_title', question: question

p = link_to 'Ask', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  = render 'common/errors', resource: @question
  p = f.label :title
  p = f.text_field :title
  p = f.label :body
  p = f.text_area :body

  p Attachments:
  p = f.fields_for :attachments do |a|
      = render 'common/attachment_fields', f: a
  .links
    = link_to_add_association 'Add more file', f, :attachments, partial: 'common/attachment_fields'
  p = f.submit 'Create'

app/views/questions/show.html.slim
.question data-question-id="#{@question.id}"
  = render @question if @question.persisted?

h3 Answers

.answers
  = render @question.answers.ordered

= form_for [@question, @answer], remote: true do |f|
  = render 'common/errors', resource: @answer
  p = f.label :body, 'Your answer:'
  p = f.text_area :body
  p
    = f.fields_for :attachments do |a|
      = render 'common/attachment_fields', f: a
    .links
      = link_to_add_association 'Add more file', f, :attachments, partial: 'common/attachment_fields'
  p = f.submit 'Answer'

app/views/questions/update.js.erb
$('#error').remove();
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
  $('.question').append('<div id="error"><%= j message %></div>');
<% end %>
<% else %>
  $('.question').html('<%= j render @question %>');
<% end %>